/**
 * Decorate the event block.
 * Handles both list-view cards and detail-view pages generated by JSON2HTML.
 * @param {Element} block the block element
 */
export default function decorate(block) {
  const container = document.createElement('div');
  container.className = 'event-container';

  // Extract heading — could be h1 (detail), h2, or h3 (list card)
  const heading = block.querySelector('h1, h2, h3');
  if (heading) {
    heading.classList.add('event-heading');
  }

  // Extract image
  const picture = block.querySelector('picture');
  if (picture) {
    const imageWrapper = document.createElement('div');
    imageWrapper.className = 'event-image';
    imageWrapper.append(picture);
    container.append(imageWrapper);
  }

  // Extract body content (everything after the image row)
  const bodyWrapper = document.createElement('div');
  bodyWrapper.className = 'event-body';

  // Get the content cells — the block has rows with div > div structure
  const rows = [...block.querySelectorAll(':scope > div')];
  rows.forEach((row) => {
    const cells = [...row.children];
    cells.forEach((cell) => {
      // Skip cells that only contained the picture (already moved)
      if (cell.children.length === 0 && cell.textContent.trim() === '') return;
      if (cell.querySelector('picture') && cell.children.length === 1) return;

      // Move remaining content to body
      while (cell.firstChild) {
        bodyWrapper.append(cell.firstChild);
      }
    });
  });

  container.append(bodyWrapper);

  // Replace block content with reorganized structure
  block.textContent = '';
  block.append(container);
}
