/**
 * Decorate the event block.
 * Handles both list-view cards and detail-view pages generated by JSON2HTML.
 * @param {Element} block the block element
 */
export default function decorate(block) {
  // Extract heading — could be h1 (detail), h2, or h3 (list card)
  const heading = block.querySelector('h1, h2, h3');
  if (heading) {
    heading.classList.add('event-heading');
  }
}
